# Generated by Django 2.2.9 on 2022-01-19 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bof',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criacao', models.DateTimeField(auto_now_add=True)),
                ('atualizacao', models.DateTimeField(auto_now_add=True)),
                ('ativo', models.BooleanField(default=True)),
                ('segmento', models.CharField(max_length=255)),
                ('produto', models.CharField(max_length=255)),
                ('modalidade', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Bof',
                'verbose_name_plural': 'Bofs',
            },
        ),
        migrations.CreateModel(
            name='Calculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criacao', models.DateTimeField(auto_now_add=True)),
                ('atualizacao', models.DateTimeField(auto_now_add=True)),
                ('ativo', models.BooleanField(default=True)),
                ('calculo', models.DecimalField(decimal_places=1, max_digits=2)),
            ],
            options={
                'verbose_name': 'Calculo',
                'verbose_name_plural': 'Calculos',
            },
        ),
        migrations.CreateModel(
            name='Calculoscombinada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criacao', models.DateTimeField(auto_now_add=True)),
                ('atualizacao', models.DateTimeField(auto_now_add=True)),
                ('ativo', models.BooleanField(default=True)),
                ('ids_calc', models.DecimalField(decimal_places=1, max_digits=2)),
            ],
            options={
                'verbose_name': 'Calculoscombinada',
                'verbose_name_plural': 'Calculoscombinadas',
            },
        ),
    ]
