# Generated by Django 2.2 on 2022-01-25 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bof',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criacao', models.DateTimeField(auto_now_add=True)),
                ('atualizacao', models.DateTimeField(auto_now_add=True)),
                ('ativo', models.BooleanField(default=True)),
                ('segmento', models.CharField(max_length=255)),
                ('produto', models.CharField(max_length=255)),
                ('modalidade', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Bof',
                'verbose_name_plural': 'Bofs',
            },
        ),
        migrations.CreateModel(
            name='Calculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criacao', models.DateTimeField(auto_now_add=True)),
                ('atualizacao', models.DateTimeField(auto_now_add=True)),
                ('ativo', models.BooleanField(default=True)),
                ('calculo', models.DecimalField(decimal_places=1, max_digits=2)),
            ],
            options={
                'verbose_name': 'Calculo',
                'verbose_name_plural': 'Calculos',
            },
        ),
        migrations.CreateModel(
            name='Calculoscombinada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criacao', models.DateTimeField(auto_now_add=True)),
                ('atualizacao', models.DateTimeField(auto_now_add=True)),
                ('ativo', models.BooleanField(default=True)),
                ('ids_calc', models.DecimalField(decimal_places=1, max_digits=2)),
            ],
            options={
                'verbose_name': 'Calculoscombinada',
                'verbose_name_plural': 'Calculoscombinadas',
            },
        ),
        migrations.CreateModel(
            name='Comboloan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criacao', models.DateTimeField(auto_now_add=True)),
                ('atualizacao', models.DateTimeField(auto_now_add=True)),
                ('ativo', models.BooleanField(default=True)),
                ('instrumento', models.CharField(max_length=255)),
                ('contraparte', models.CharField(max_length=255)),
                ('deriv', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Comboloan',
                'verbose_name_plural': 'Comboloans',
            },
        ),
        migrations.CreateModel(
            name='Dadoscalculadorapipeline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criacao', models.DateTimeField(auto_now_add=True)),
                ('atualizacao', models.DateTimeField(auto_now_add=True)),
                ('ativo', models.BooleanField(default=True)),
                ('id_calculadora', models.DecimalField(decimal_places=1, max_digits=2)),
                ('produto', models.CharField(default='', max_length=255)),
            ],
            options={
                'verbose_name': 'Dadoscalculadorapipeline',
                'verbose_name_plural': 'Dadoscalculadorapipelines',
            },
        ),
        migrations.CreateModel(
            name='Dgabaseoperacoes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criacao', models.DateTimeField(auto_now_add=True)),
                ('atualizacao', models.DateTimeField(auto_now_add=True)),
                ('ativo', models.BooleanField(default=True)),
                ('cliente', models.CharField(default='', max_length=255)),
            ],
            options={
                'verbose_name': 'Dgabaseoperacoes',
                'verbose_name_plural': 'Dgabaseoperacoess',
            },
        ),
        migrations.CreateModel(
            name='Dgaceadiario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criacao', models.DateTimeField(auto_now_add=True)),
                ('atualizacao', models.DateTimeField(auto_now_add=True)),
                ('ativo', models.BooleanField(default=True)),
                ('cliente', models.CharField(default='', max_length=255)),
            ],
            options={
                'verbose_name': 'Dgaceadiario',
                'verbose_name_plural': 'Dgaceadiarios',
            },
        ),
        migrations.CreateModel(
            name='Dgacurvasjuros',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criacao', models.DateTimeField(auto_now_add=True)),
                ('atualizacao', models.DateTimeField(auto_now_add=True)),
                ('ativo', models.BooleanField(default=True)),
                ('moeda', models.DecimalField(decimal_places=1, max_digits=2)),
                ('prazo', models.DecimalField(decimal_places=1, max_digits=2)),
                ('index', models.CharField(default='', max_length=255)),
            ],
            options={
                'verbose_name': 'Dgacurvasjuros',
                'verbose_name_plural': 'Dgacurvasjuross',
            },
        ),
        migrations.CreateModel(
            name='Dgagrupos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criacao', models.DateTimeField(auto_now_add=True)),
                ('atualizacao', models.DateTimeField(auto_now_add=True)),
                ('ativo', models.BooleanField(default=True)),
                ('racf', models.CharField(default='', max_length=255)),
                ('carteira', models.CharField(default='', max_length=255)),
            ],
            options={
                'verbose_name': 'Dgagrupos',
                'verbose_name_plural': 'Dgagruposs',
            },
        ),
        migrations.CreateModel(
            name='Dgamatrizmigracao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criacao', models.DateTimeField(auto_now_add=True)),
                ('atualizacao', models.DateTimeField(auto_now_add=True)),
                ('ativo', models.BooleanField(default=True)),
                ('id_grupo', models.CharField(default='', max_length=255)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('mes', models.CharField(default='', max_length=255)),
                ('segmento', models.CharField(default='', max_length=255)),
            ],
            options={
                'verbose_name': 'Dgamatrizmigracao',
                'verbose_name_plural': 'Dgamatrizmigracaos',
            },
        ),
        migrations.CreateModel(
            name='Cboregracusteio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criacao', models.DateTimeField(auto_now_add=True)),
                ('atualizacao', models.DateTimeField(auto_now_add=True)),
                ('ativo', models.BooleanField(default=True)),
                ('modalidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modalidades', to='CalculatorIrarocAPI.Bof')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='CalculatorIrarocAPI.Bof')),
            ],
            options={
                'verbose_name': 'Cboregracusteio',
                'verbose_name_plural': 'Cboregracusteios',
            },
        ),
    ]
