# Generated by Django 2.2 on 2022-01-25 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CalculatorIrarocAPI', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dgamontecarlo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criacao', models.DateTimeField(auto_now_add=True)),
                ('atualizacao', models.DateTimeField(auto_now_add=True)),
                ('ativo', models.BooleanField(default=True)),
                ('atv', models.CharField(default='', max_length=50)),
                ('passivo', models.CharField(default='', max_length=50)),
            ],
            options={
                'verbose_name': 'Dgamontecarlo',
                'verbose_name_plural': 'Dgamontecarlos',
            },
        ),
        migrations.AlterModelOptions(
            name='dgamatrizmigracao',
            options={'verbose_name': 'Dgamatrizmigracao', 'verbose_name_plural': 'Dgamatrizmigracoes'},
        ),
    ]
