# Generated by Django 2.2.9 on 2022-01-19 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CalculatorIrarocAPI', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Calculoscombinada',
        ),
    ]
