# Generated by Django 2.2.9 on 2022-01-19 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CalculatorIrarocAPI', '0003_calculoscombinada'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cboregracusteio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criacao', models.DateTimeField(auto_now_add=True)),
                ('atualizacao', models.DateTimeField(auto_now_add=True)),
                ('ativo', models.BooleanField(default=True)),
                ('modalidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modalidades', to='CalculatorIrarocAPI.Bof')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='CalculatorIrarocAPI.Bof')),
            ],
            options={
                'verbose_name': 'Cboregracusteio',
                'verbose_name_plural': 'Cboregracusteios',
            },
        ),
    ]
