# Generated by Django 2.2 on 2022-01-26 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CalculatorIrarocAPI', '0003_dgaparametrosestrategiaportfolio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dgapercentualfepf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criacao', models.DateTimeField(auto_now_add=True)),
                ('atualizacao', models.DateTimeField(auto_now_add=True)),
                ('ativo', models.BooleanField(default=True)),
                ('classe', models.CharField(default='', max_length=50)),
                ('prazo', models.IntegerField(default='')),
            ],
            options={
                'verbose_name': 'Dgapercentualfepf',
                'verbose_name_plural': 'Dgapercentualfepfs',
            },
        ),
    ]
