# Generated by Django 2.2 on 2022-01-26 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CalculatorIrarocAPI', '0004_dgapercentualfepf'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dgarcpalfasbetas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criacao', models.DateTimeField(auto_now_add=True)),
                ('atualizacao', models.DateTimeField(auto_now_add=True)),
                ('ativo', models.CharField(default='', max_length=50)),
                ('passivo', models.CharField(default='', max_length=50)),
                ('racf', models.CharField(default='', max_length=50)),
            ],
            options={
                'verbose_name': 'dgarcpalfasbetas',
                'verbose_name_plural': 'dgarcpalfasbetass',
            },
        ),
    ]
