# Generated by Django 2.2 on 2022-01-26 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CalculatorIrarocAPI', '0005_dgarcpalfasbetas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dgatargetpais',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criacao', models.DateTimeField(auto_now_add=True)),
                ('atualizacao', models.DateTimeField(auto_now_add=True)),
                ('ativo', models.BooleanField(default=True)),
                ('pais', models.CharField(default='', max_length=2)),
            ],
            options={
                'verbose_name': 'dgatargetpais',
                'verbose_name_plural': 'dgatargetpaiss',
            },
        ),
    ]
