# Generated by Django 2.2 on 2022-01-26 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CalculatorIrarocAPI', '0006_dgatargetpais'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fprcnpj',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criacao', models.DateTimeField(auto_now_add=True)),
                ('atualizacao', models.DateTimeField(auto_now_add=True)),
                ('ativo', models.BooleanField(default=True)),
                ('cnpj', models.CharField(default='', max_length=14)),
            ],
            options={
                'verbose_name': 'fprcnpj',
                'verbose_name_plural': 'fprcnpjs',
            },
        ),
    ]
